# Spring Profile:
spring.application.name=Personal-financier

# Server settings
server.port=${PORT:8080}
server.address=${SERVER_ADDRESS:localhost}

# Active profile
spring.profiles.active=${SPRING_CONFIG_ACTIVATE_ON_PROFILE}
spring.config.import=optional:file:.env[.properties]

# JWT
jwt.secret=${SECRET_KEY}
jwt.expiration=86400000

#Flyway:
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_ADDRESS:FinalProjectLinkedin@gmail.com}
spring.mail.password=${EMAIL_PASSWORD:x q j h l e m v t j f x g g p o}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

