spring.config.activate.on-profile=local

# DB
spring.datasource.url=jdbc:postgresql://localhost:5432/financeDB
spring.datasource.username=postgres
spring.datasource.password=prsfin123
spring.datasource.driverClassName=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# SQL
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE

# Mail
spring.mail.host=smtp.local.example.com
spring.mail.port=587
spring.mail.username=local_email@example.com
spring.mail.password=local_password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
