spring.config.activate.on-profile=local

# DB
spring.datasource.url=jdbc:postgresql://localhost:5432/financeDB
spring.datasource.username=postgres
spring.datasource.password=prsfin123
spring.datasource.driverClassName=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# SQL - Logging
logging.level.org.springframework.mail=DEBUG
logging.level.jakarta.mail=DEBUG
logging.level.com.sun.mail=DEBUG
spring.mail.properties.mail.debug=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE
logging.level.org.springframework.security=DEBUG

## Mail
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=${MAIL_ADDRESS:FinalProjectLinkedin@gmail.com}
#spring.mail.password=${MAIL_PASSWORD:upiv trwk upsc snjo}
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true

app.security.cors.allowed-origins=http://localhost:3000
